const products=[{id:1,name:'轻氧焕亮面霜',price:'¥129',desc:'轻薄保湿，适合日常护理',keywords:['面霜','保湿','敏感肌','护肤']},{id:2,name:'云感洁面慕斯',price:'¥59',desc:'泡沫细腻，洗后不紧绷',keywords:['洁面','洗脸','泡沫']},{id:3,name:'晚安修护面膜',price:'¥89',desc:'夜间修护，单片独立包装',keywords:['面膜','修护','补水']}];
let selectedProduct=products[0], currentScript='', speaking=true, queue=[];const seenCommentIds=new Set();
const $=s=>document.querySelector(s); const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderProducts(){ $('#productList').innerHTML=products.map(p=>`<div class="product ${p.id===selectedProduct.id?'selected':''}" data-id="${p.id}"><div class="product-top"><b>${p.name}</b><span class="price">${p.price}</span></div><p>${p.desc}</p></div>`).join(''); document.querySelectorAll('.product').forEach(e=>e.onclick=()=>{selectedProduct=products.find(p=>p.id==e.dataset.id);renderProducts();}); }
function addComment(text,name='',eventType='comment',avatarUrl='',id='',replay=false){if(!text.trim()||(id&&seenCommentIds.has(String(id))))return;if(id){seenCommentIds.add(String(id));if(seenCommentIds.size>300)seenCommentIds.delete(seenCommentIds.values().next().value)} const item={id,text:text.trim(),name:name||['小鹿','阿楠','橘子汽水','小麦'][Math.floor(Math.random()*4)],eventType,avatarUrl:/^https?:\/\//.test(avatarUrl)?avatarUrl:'',time:new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}; queue.push(item);if(queue.length>100)queue.shift();renderQueue();if(eventType==='comment'&&!replay)generate(item);}
function renderQueue(){ $('#queueCount').textContent=`${queue.length} 条消息`; $('#commentList').innerHTML=queue.slice().reverse().map((c,i)=>`<div class="comment ${i===0?'active':''} ${c.eventType==='member'?'member-event':''}" data-text="${esc(c.text)}" data-event-type="${c.eventType}"><span class="name">${c.avatarUrl?`<img class="comment-avatar" src="${esc(c.avatarUrl)}" alt="" referrerpolicy="no-referrer">`:`<span class="comment-avatar avatar-placeholder">${c.eventType==='member'?'👋':'👤'}</span>`}${esc(c.name)}</span><span class="time">${c.time}</span><p>${esc(c.text)}</p></div>`).join('')||'<div style="color:#9aa4a0;font-size:13px;padding:35px 0;text-align:center">等待评论进入队列…</div>'; document.querySelectorAll('.comment').forEach(e=>e.onclick=()=>{if(e.dataset.eventType==='comment')generate({text:e.dataset.text,name:'观众'})});}
function generate(item){const q=item.text;let p=selectedProduct; if(/洁面|洗脸|泡/.test(q))p=products[1]; else if(/面膜|修护|补水/.test(q))p=products[2]; selectedProduct=p;renderProducts();let s;if(/多少|价格|钱|优惠/.test(q))s=`这款${p.name}现在是${p.price}，直播间下单会有专属优惠，大家可以点开商品卡看当前活动。`;else if(/敏感|能用吗|适合/.test(q))s=`如果你是敏感肌，建议先在耳后做局部测试。这款${p.name}主打${p.desc}，具体还是以自己的肤质感受为准。`;else if(/发货|快递|什么时候/.test(q))s='正常情况下会尽快安排发出，具体以商品详情页显示的发货时效为准，大家也可以联系客服确认。';else s=`很多朋友在问${p.name}，它的特点是${p.desc}。有具体问题可以继续留言，我帮大家一起看。`; currentScript=s;$('#suggestedScript').textContent=s;$('#speechProduct').textContent=p.name;$('#modeTag').textContent='已生成';}
function onAudioStart(){$('#modeTag').textContent='播报中';$('#currentSpeech').textContent=currentScript;$('#speechTime').textContent='刚刚';$('#wave').classList.add('playing')}
function onAudioEnd(){$('#modeTag').textContent='待机';$('#wave').classList.remove('playing')}
function fallbackSpeak(){const u=new SpeechSynthesisUtterance(currentScript);u.lang='zh-CN';u.rate=.95;u.onstart=onAudioStart;u.onend=onAudioEnd;speechSynthesis.speak(u)}
async function speak(){if(!currentScript)return;if(!speaking){$('#modeTag').textContent='已暂停';return}speechSynthesis.cancel();const audio=$('#ttsAudio');audio.pause();$('#modeTag').textContent='生成语音…';$('#voiceState').textContent='豆包 2.0 正在合成';try{const r=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:currentScript,voice:$('#voiceSelect').value,context:'reply'})});const data=await r.json();if(!r.ok)throw new Error(data.error||'tts');audio.src=data.url;audio.onplay=onAudioStart;audio.onended=onAudioEnd;await audio.play();$('#voiceState').textContent=data.warning||'豆包语音合成 2.0'}catch(e){$('#voiceState').textContent='已回退本机语音';fallbackSpeak()}}
$('#replyBtn').onclick=()=>{addComment($('#commentInput').value);$('#commentInput').value=''};$('#commentInput').onkeydown=e=>{if(e.key==='Enter')$('#replyBtn').click()};document.querySelectorAll('.quick button').forEach(b=>b.onclick=()=>addComment(b.dataset.q));$('#speakBtn').onclick=speak;$('#soundBtn').onclick=()=>{speaking=!speaking;$('#soundBtn').textContent=`声音：${speaking?'开':'关'}`;};$('#stopBtn').onclick=()=>{speechSynthesis.cancel();speaking=false;$('#modeTag').textContent='已停止';$('#soundBtn').textContent='声音：关';$('#wave').classList.remove('playing')};$('#copyBtn').onclick=async()=>{if(currentScript)await navigator.clipboard.writeText(currentScript);$('#copyBtn').textContent='已复制';setTimeout(()=>$('#copyBtn').textContent='复制',1200)};$('#addBtn').onclick=()=>alert('商品管理将在下一版开放。当前版本可直接点击商品切换。');renderProducts();
const commentStream=new EventSource('/api/comment-events');commentStream.addEventListener('open',()=>{const chip=$('#douyinStreamState');if(chip)chip.textContent='本地消息通道已连接'});commentStream.addEventListener('comment',event=>{const data=JSON.parse(event.data);addComment(data.content,data.userName,data.eventType,data.avatarUrl,data.id,data.replay);if(data.eventType==='member'&&!data.replay)window.dispatchEvent(new CustomEvent('live-member-entered',{detail:data}));const chip=$('#douyinStreamState');if(chip)chip.textContent=data.eventType==='member'?`${data.userName} 进入了直播间`:`刚收到 ${data.userName} 的消息`});commentStream.onerror=()=>{const chip=$('#douyinStreamState');if(chip)chip.textContent='本地消息通道正在重连…'};
