(function(){
  const list=document.getElementById('giftEventList');if(!list)return;const events=[],speechQueue=[],pendingGifts=[],audio=new Audio();let busy=false,batchTimer=0;
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function render(){document.getElementById('giftQueueState').textContent=events.length?`${events.length} 条礼物记录`:'等待礼物';list.innerHTML=events.length?events.slice().reverse().map(e=>`<article class="gift-event ${e.speaking?'speaking':''}" data-id="${e.id}">${e.avatarUrl?`<span class="gift-icon"><img src="${esc(e.avatarUrl)}" alt="" referrerpolicy="no-referrer"></span>`:'<span class="gift-icon">🎁</span>'}<div><b>${esc(e.userName)}</b><small>送出 ${e.count} × ${esc(e.giftName)}</small></div><button class="gift-replay">播放话术</button><p>${esc(e.reply)}</p></article>`).join(''):'<div class="gift-empty">收到礼物后，感谢话术会出现在这里。</div>'}
  function stage(e,state){document.getElementById('suggestedScript').textContent=e.reply;document.getElementById('speechProduct').textContent=`🎁 ${e.giftName} × ${e.count}`;document.getElementById('currentSpeech').textContent=e.reply;document.getElementById('modeTag').textContent=state;document.getElementById('speechTime').textContent=e.userName;document.getElementById('wave').classList.toggle('playing',state==='礼物播报中')}
  function combine(items){if(items.length===1)return {...items[0],members:items};const shown=items.slice(0,6).map(x=>`感谢${x.userName}送的${x.count}个${x.giftName}`).join('，'),more=items.length>6?`，还要感谢另外${items.length-6}位朋友送的礼物`:'';return {id:`batch-${Date.now()}`,userName:`${items.length}位朋友`,giftName:'多份礼物',count:items.reduce((n,x)=>n+x.count,0),reply:`${shown}${more}`,members:items}}
  function speak(e,immediate=false){if(immediate){speechQueue.push({...e,members:[e]});runQueue();return}pendingGifts.push(e);if(pendingGifts.length===1)batchTimer=setTimeout(()=>{speechQueue.push(combine(pendingGifts.splice(0)));runQueue()},2000)}
  async function runQueue(){if(busy||!speechQueue.length)return;busy=true;const e=speechQueue.shift();for(const item of e.members||[e])item.speaking=true;render();stage(e,'礼物语音生成中');try{const voice='zh-CN-XiaoxiaoNeural',r=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:e.reply,voice,rate:'+40%',context:'reply'})}),d=await r.json();if(!r.ok)throw new Error(d.error||'礼物语音生成失败');audio.src=d.url;const play=async()=>{await audio.play();stage(e,'礼物播报中');await new Promise(resolve=>{audio.onended=resolve;audio.onerror=resolve})};if(window.LiveAudioFocus?.runExclusive)await window.LiveAudioFocus.runExclusive(audio,play);else await play()}catch(err){document.getElementById('giftQueueState').textContent=err.message}finally{for(const item of e.members||[e])item.speaking=false;busy=false;stage(e,'待机');render();if(pendingGifts.length){clearTimeout(batchTimer);speechQueue.push(combine(pendingGifts.splice(0)))}if(speechQueue.length)runQueue()}}
  function receive(e){if(events.some(x=>x.id===e.id))return;events.push(e);if(events.length>50)events.shift();render();if(!e.replay){window.dispatchEvent(new CustomEvent('live-gift-received',{detail:e}));stage(e,'收到礼物');if(document.getElementById('giftAutoSpeak').checked&&String(e.giftName||'').trim()!=='小心心')speak(e)}}
  const stream=new EventSource('/api/gift-events');stream.addEventListener('open',()=>{document.querySelector('.gift-connect-state').classList.add('connected');document.getElementById('giftConnectState').textContent='礼物事件接收接口已连接'});stream.addEventListener('gift',e=>receive(JSON.parse(e.data)));stream.onerror=()=>{document.querySelector('.gift-connect-state').classList.remove('connected');document.getElementById('giftConnectState').textContent='礼物事件流正在重连…'};
  document.getElementById('simulateGift').onclick=async()=>{const payload={userName:document.getElementById('giftUser').value.trim(),giftName:document.getElementById('giftName').value.trim(),count:Number(document.getElementById('giftCount').value)||1,value:Number(document.getElementById('giftValue').value)||0};const r=await fetch('/api/douyin/gift-event',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)document.getElementById('giftQueueState').textContent=d.error||'模拟失败'};
  list.onclick=e=>{const card=e.target.closest('.gift-event');if(card&&e.target.closest('.gift-replay')){const item=events.find(x=>String(x.id)===card.dataset.id);if(item)speak(item,true)}};
})();
