(function(){
  const bridge=window.LiveHistoryAudio,section=document.querySelector('.script-history');if(!bridge||!section)return;const audio=bridge.audio;let context,analyser,source,raf;const probing=new Set();
  const time=n=>Number.isFinite(n)?`${String(Math.floor(n/60)).padStart(2,'0')}:${String(Math.floor(n%60)).padStart(2,'0')}`:'00:00';
  function panel(){const id=bridge.getPlayingId();return id?section.querySelector(`.script-history-card[data-id="${id}"] .history-audio-panel`):null}
  function mount(){const id=bridge.getPlayingId();if(!id)return;const card=section.querySelector(`.script-history-card[data-id="${id}"]`);if(!card||card.querySelector('.history-audio-panel'))return;card.insertAdjacentHTML('beforeend',`<div class="history-audio-panel"><canvas class="history-wave" width="900" height="74"></canvas><div class="history-track"><span class="history-current">${time(audio.currentTime)}</span><input class="history-progress" type="range" min="0" max="${audio.duration||0}" step="0.01" value="${audio.currentTime||0}"><span class="history-total">${time(audio.duration)}</span></div><div class="history-audio-state"><span class="history-playing-label">正在播放这篇直播稿</span><span class="history-live-volume">实时声音</span></div></div>`);sync();draw()}
  function ensure(){if(!context){context=new AudioContext();source=context.createMediaElementSource(audio);analyser=context.createAnalyser();analyser.fftSize=128;analyser.smoothingTimeConstant=.72;source.connect(analyser);analyser.connect(context.destination)}context.resume()}
  function cachedVoice(item){return item.selectedVoice||Object.keys(item.audios||{})[0]||''}
  function decorateTitles(){const records=bridge.getHistory(),knownProduct=records.find(x=>x.productName&&x.productName!=='当前商品')?.productName||document.getElementById('scriptName')?.value.trim();let changed=false;for(const card of section.querySelectorAll('.script-history-card')){const item=records.find(x=>x.id===card.dataset.id),title=card.querySelector('.script-history-title');if(!item||!title)continue;const heading=item.text?.match(/【商品名称[：:]\s*([^】]+)】/),parts=String(item.title||'').split('｜'),titleProduct=parts.length>1?parts[0]:'',product=(item.productName&&item.productName!=='当前商品'?item.productName:heading?.[1]||titleProduct||knownProduct||'当前商品').trim(),core=(parts.length>1?parts.slice(1).join('｜'):item.title||'直播讲解').trim(),key=`${product}|${core}`;if(product!=='当前商品'&&item.productName!==product){item.productName=product;changed=true}if(title.dataset.productTitle===key)continue;title.dataset.productTitle=key;title.textContent='';const productEl=document.createElement('span'),coreEl=document.createElement('span');productEl.className='script-product-name';productEl.textContent=product;coreEl.className='script-core-title';coreEl.textContent=core;title.append(productEl,coreEl)}if(changed)bridge.save()}
  function voiceName(card,voice){return [...(card.querySelector('.history-voice')?.options||[])].find(o=>o.value===voice)?.textContent||voice}
  function probeDuration(item,voice,url){const key=`${item.id}|${voice}`;if(probing.has(key)||!url)return;probing.add(key);const probe=new Audio();probe.preload='metadata';probe.onloadedmetadata=()=>{item.audioDurations=item.audioDurations||{};item.audioDurations[voice]=probe.duration;item.selectedVoice=item.selectedVoice||voice;bridge.save();probing.delete(key);decorate()};probe.onerror=()=>probing.delete(key);probe.src=url}
  function decorate(){for(const card of section.querySelectorAll('.script-history-card')){const item=bridge.getHistory().find(x=>x.id===card.dataset.id);if(!item)continue;const voice=cachedVoice(item),url=item.audios?.[voice],cache=card.querySelector('.history-cache'),select=card.querySelector('.history-voice');if(voice&&select){select.value=voice;item.selectedVoice=item.selectedVoice||voice;const button=select._voiceButton;if(button){const name=button.querySelector('.voice-picker-name'),tip=button.querySelector('.voice-picker-tip'),label=voiceName(card,voice);if(name&&name.textContent!==label)name.textContent=label;const tipLabel=url?'缓存音色 ✓':'选择音色 ›';if(tip&&tip.textContent!==tipLabel)tip.textContent=tipLabel}}if(cache){if(url){const duration=item.audioDurations?.[voice],markCount=item.audioSentenceMarks?.[voice]?.length||0,label=`缓存：${voiceName(card,voice)}${Number.isFinite(duration)?` · ${time(duration)}`:''}${markCount?` · ${markCount}个句尾`:''}`;if(cache.textContent!==label)cache.textContent=label;if(!Number.isFinite(duration))probeDuration(item,voice,url)}else if(cache.textContent!=='尚未合成音频')cache.textContent='尚未合成音频'}}}
  function sync(){const p=panel();if(!p)return;const slider=p.querySelector('.history-progress');slider.max=audio.duration||0;slider.value=audio.currentTime||0;p.querySelector('.history-current').textContent=time(audio.currentTime);p.querySelector('.history-total').textContent=time(audio.duration)}
  function draw(){cancelAnimationFrame(raf);if(!analyser||audio.paused)return;const data=new Uint8Array(analyser.frequencyBinCount);const loop=()=>{const p=panel();if(!p||audio.paused)return;const canvas=p.querySelector('.history-wave'),ctx=canvas.getContext('2d');analyser.getByteFrequencyData(data);ctx.clearRect(0,0,canvas.width,canvas.height);const count=52,gap=5,w=(canvas.width-gap*(count-1))/count,ratio=audio.duration?audio.currentTime/audio.duration:0;for(let i=0;i<count;i++){const level=data[Math.floor(i*data.length/count)]/255,h=Math.max(5,level*canvas.height*.9);ctx.fillStyle=i/count<ratio?'#c9f05b':'#0b6b63';ctx.fillRect(i*(w+gap),(canvas.height-h)/2,w,h)}raf=requestAnimationFrame(loop)};loop()}
  audio.addEventListener('play',()=>{ensure();setTimeout(()=>{mount();draw();decorate();decorateTitles()},0)});audio.addEventListener('timeupdate',sync);audio.addEventListener('loadedmetadata',()=>{const item=bridge.getHistory().find(x=>x.id===bridge.getPlayingId()),voice=item&&cachedVoice(item);if(item&&voice&&Number.isFinite(audio.duration)){item.audioDurations=item.audioDurations||{};item.audioDurations[voice]=audio.duration;bridge.save()}mount();sync();decorate();decorateTitles()});audio.addEventListener('ended',()=>cancelAnimationFrame(raf));section.addEventListener('input',e=>{if(e.target.matches('.history-progress')&&Number.isFinite(audio.duration))audio.currentTime=Number(e.target.value)});new MutationObserver(()=>{decorate();decorateTitles();if(!audio.paused)mount()}).observe(section,{childList:true,subtree:true});decorate();decorateTitles();
  window.addEventListener('gift-boundary-target',e=>{if(e.detail.audio!==audio)return;const p=panel(),track=p?.querySelector('.history-track');if(track&&e.detail.duration){track.classList.add('pending-boundary');track.style.setProperty('--gift-marker',`${Math.min(100,e.detail.target/e.detail.duration*100)}%`)}});window.addEventListener('gift-boundary-clear',e=>{if(e.detail.audio!==audio)return;panel()?.querySelector('.history-track')?.classList.remove('pending-boundary')});
})();
