(function(){
  const out=document.getElementById('scriptOutput');if(!out)return;
  const bar=document.createElement('div');bar.className='narration-bar';
  bar.innerHTML='<div class="narration-controls"><select id="scriptVoice"><option value="zh_female_gaolengyujie_uranus_bigtts">豆包 2.0 · 自然御姐声</option><option value="zh-CN-XiaoxiaoNeural">备用 · 晓晓女声</option><option value="zh-CN-XiaoyiNeural">备用 · 晓伊女声</option><option value="zh-CN-YunxiNeural">备用 · 云希男声</option><option value="zh-CN-YunjianNeural">备用 · 云健男声</option></select><button id="narrateScript">▶ 生成并播报</button><button id="replayNarration">↻ 重播</button><button id="pauseNarration">暂停</button><button id="stopNarration">停止</button></div><div class="audio-track"><canvas id="waveCanvas" width="900" height="90"></canvas><div class="track-line"><span id="currentTime">00:00</span><input id="audioProgress" type="range" min="0" max="1000" value="0"><span id="totalTime">00:00</span></div></div><span id="narrationState">等待稿件</span><audio id="scriptAudio" preload="metadata"></audio>';
  out.parentElement.appendChild(bar);bar.querySelector('.narration-controls').style.gridTemplateColumns='1fr auto auto auto auto';
  const audio=document.getElementById('scriptAudio'),progress=document.getElementById('audioProgress'),canvas=document.getElementById('waveCanvas'),ctx=canvas.getContext('2d');let marks=[];window.LiveAudioFocus?.register(audio,{getSentenceMarks:()=>marks,onState:state=>document.getElementById('narrationState').textContent=state});let stopped=false,audioContext,analyser,source,raf;
  const time=n=>{if(!Number.isFinite(n))return'00:00';const m=Math.floor(n/60),s=Math.floor(n%60);return`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`};
  function drawPlaceholder(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#d9e5df';for(let x=2;x<canvas.width;x+=7){const h=8+Math.sin(x*.09)*5;ctx.fillRect(x,(canvas.height-h)/2,3,h)}}drawPlaceholder();
  function setupAnalyser(){if(!audioContext){audioContext=new AudioContext();source=audioContext.createMediaElementSource(audio);analyser=audioContext.createAnalyser();analyser.fftSize=128;analyser.smoothingTimeConstant=.72;source.connect(analyser);analyser.connect(audioContext.destination)}audioContext.resume();cancelAnimationFrame(raf);const data=new Uint8Array(analyser.frequencyBinCount);const draw=()=>{raf=requestAnimationFrame(draw);analyser.getByteFrequencyData(data);ctx.clearRect(0,0,canvas.width,canvas.height);const count=48,gap=5,w=(canvas.width-gap*(count-1))/count;for(let i=0;i<count;i++){const v=data[Math.floor(i*data.length/count)]/255,h=Math.max(5,v*canvas.height*.92),x=i*(w+gap);ctx.fillStyle=i/count<(audio.duration?audio.currentTime/audio.duration:0)?'#c9f05b':'#0b6b63';ctx.fillRect(x,(canvas.height-h)/2,w,h)}};draw()}
  async function play(){const text=out.value.replace(/【[^】]+】/g,'').replace(/\n{3,}/g,'\n\n').trim();if(!text)return;const generateButton=document.getElementById('narrateScript');const state=document.getElementById('narrationState');stopped=false;generateButton.disabled=true;generateButton.textContent='⏳ 合成中…';state.textContent='豆包 2.0 正在合成整篇连续语音…';try{const r=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:text.slice(0,4800),voice:document.getElementById('scriptVoice').value,rate:'-4%',pitch:'+0Hz',context:'live'})});const d=await r.json();if(!r.ok)throw new Error(d.error||'语音生成失败');if(stopped)return;marks=Array.isArray(d.sentenceMarks)?d.sentenceMarks:[];audio.src=d.url;audio.load();setupAnalyser();state.textContent=d.warning||`豆包 2.0 正在连续播报整篇直播稿${marks.length?` · ${marks.length} 个句尾标记`:''}`;await audio.play()}finally{generateButton.disabled=false;generateButton.textContent='▶ 生成并播报'}}
  audio.onloadedmetadata=()=>{progress.max=audio.duration||0;document.getElementById('totalTime').textContent=time(audio.duration)};
  audio.ontimeupdate=()=>{progress.value=audio.currentTime;document.getElementById('currentTime').textContent=time(audio.currentTime);window.dispatchEvent(new CustomEvent('narration-progress',{detail:{ratio:audio.duration?audio.currentTime/audio.duration:0}}))};
  audio.onended=()=>document.getElementById('narrationState').textContent='直播稿播报完成';
  progress.oninput=()=>{if(Number.isFinite(audio.duration)){audio.currentTime=Number(progress.value);document.getElementById('currentTime').textContent=time(audio.currentTime)}};
  window.addEventListener('segment-jump',e=>{if(audio.src&&Number.isFinite(audio.duration)){audio.currentTime=audio.duration*e.detail.ratio;progress.value=audio.currentTime;document.getElementById('narrationState').textContent=`已跳转到：${e.detail.title}`}});
  document.getElementById('narrateScript').onclick=()=>play().catch(e=>document.getElementById('narrationState').textContent=e.message);
  document.getElementById('replayNarration').onclick=()=>{if(!audio.src)return;stopped=false;audio.currentTime=0;progress.value=0;setupAnalyser();audio.play();document.getElementById('pauseNarration').textContent='暂停';document.getElementById('narrationState').textContent='正在从头重播'};
  document.getElementById('pauseNarration').onclick=e=>{if(!audio.src)return;if(window.LiveAudioFocus?.isExclusiveActive()&&audio.paused){window.LiveAudioFocus.cancelResume(audio);e.target.textContent='继续';document.getElementById('narrationState').textContent='已手动暂停，礼物结束后不会自动恢复';return}if(audio.paused){audio.play();e.target.textContent='暂停';document.getElementById('narrationState').textContent='继续播报'}else{window.LiveAudioFocus?.cancelResume(audio);audio.pause();e.target.textContent='继续';document.getElementById('narrationState').textContent='已暂停'}};
  document.getElementById('stopNarration').onclick=()=>{stopped=true;window.LiveAudioFocus?.cancelResume(audio);audio.pause();audio.currentTime=0;progress.value=0;document.getElementById('narrationState').textContent='已停止'};
  window.addEventListener('gift-boundary-target',e=>{if(e.detail.audio!==audio)return;const track=bar.querySelector('.track-line');if(e.detail.duration){track.classList.add('pending-boundary');track.style.setProperty('--gift-marker',`${Math.min(100,e.detail.target/e.detail.duration*100)}%`)}});window.addEventListener('gift-boundary-clear',e=>{if(e.detail.audio===audio)bar.querySelector('.track-line').classList.remove('pending-boundary')});
})();
