(function(){
  const byId=id=>document.getElementById(id), STORAGE_KEY='liveScriptHistoryV1';
  const voiceOptions=[['zh_female_gaolengyujie_uranus_bigtts','豆包 2.0 · 自然御姐声'],['zh-CN-XiaoxiaoNeural','备用 · 晓晓女声'],['zh-CN-XiaoyiNeural','备用 · 晓伊女声'],['zh-CN-YunxiNeural','备用 · 云希男声'],['zh-CN-YunjianNeural','备用 · 云健男声']];
  let history=[];try{history=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch{history=[]}let playingId='',globalLoop=false,globalIndex=0,globalOrder=[];const audioJobs=new Map(),historyAudio=new Audio();window.LiveAudioFocus?.register(historyAudio,{getSentenceMarks:()=>{const item=history.find(x=>x.id===playingId),voice=item&&selectedVoice(item);return voice?item.audioSentenceMarks?.[voice]||[]:[]},onState:state=>{const el=document.querySelector('.global-play-status');if(el)el.textContent=state}});window.LiveHistoryAudio={audio:historyAudio,getPlayingId:()=>playingId,getHistory:()=>history,save:()=>save(),getRate:()=>currentRate()};
  const val=(id,fallback)=>byId(id).value.trim()||fallback;
  const formButton=byId('makeScript'),actionWrap=document.createElement('div');actionWrap.className='script-generate-actions';formButton.parentNode.insertBefore(actionWrap,formButton);actionWrap.appendChild(formButton);const continueButton=document.createElement('button');continueButton.type='button';continueButton.className='primary continue-script';continueButton.textContent='基于当前稿件续写下一篇 →';actionWrap.appendChild(continueButton);
  const lengthSetting=document.createElement('label');lengthSetting.className='script-length-setting';lengthSetting.innerHTML='<span>全局单篇稿件长度<br><small>适用于首次生成和后续续写</small></span><input id="scriptTargetLength" type="number" min="10" max="3000" step="10" value="1000">';actionWrap.parentNode.insertBefore(lengthSetting,actionWrap);const lengthInput=lengthSetting.querySelector('input');lengthInput.value=localStorage.getItem('liveScriptTargetLength')||'1000';lengthInput.addEventListener('change',()=>{lengthInput.value=String(Math.min(3000,Math.max(10,Number(lengthInput.value)||1000)));localStorage.setItem('liveScriptTargetLength',lengthInput.value)});
  const section=document.createElement('section');section.className='script-history';section.innerHTML='<div class="script-history-head"><div><span class="kicker">连续直播稿件</span><h3>已经生成的稿件</h3></div><div class="script-history-head-right"><button class="script-head-action new-script-button">＋ 新建稿件</button><button class="script-head-action continue-head-button">基于最后一篇续写</button><label class="global-rate-wrap">全局语速<select class="global-rate"><option value="0.8">较慢 0.8×</option><option value="0.9">稍慢 0.9×</option><option value="1">自然语速</option><option value="1.1">稍快 1.1×</option><option value="1.2">较快 1.2×</option><option value="1.3">快速 1.3×</option></select></label><button class="global-skip global-prev">← 上一篇</button><button class="global-skip global-next">下一篇 →</button><span class="global-play-status">从最下面开始顺序播放</span><button class="global-play">▶ 无限循环播放</button><span class="script-history-count"></span></div></div><div class="script-history-list"></div>';document.querySelector('.script-maker').appendChild(section);
  const globalButton=section.querySelector('.global-play'),prevButton=section.querySelector('.global-prev'),nextButton=section.querySelector('.global-next'),newScriptButton=section.querySelector('.new-script-button'),continueHeadSlot=section.querySelector('.continue-head-button'),globalStatus=section.querySelector('.global-play-status'),globalRate=section.querySelector('.global-rate');continueButton.remove();continueHeadSlot.replaceWith(continueButton);continueButton.className='script-head-action continue-head-button';continueButton.textContent='基于最后一篇续写';const savedRate=localStorage.getItem('liveGlobalSpeechRate');globalRate.value=savedRate&&/^[0-9.]+$/.test(savedRate)?savedRate:'1';const currentRate=()=>Number(globalRate.value)||1;historyAudio.preservesPitch=true;globalRate.addEventListener('change',()=>{localStorage.setItem('liveGlobalSpeechRate',currentRate());historyAudio.playbackRate=currentRate();if(!historyAudio.paused)globalStatus.textContent=`播放速度已调整为 ${currentRate()}×`});
  const makerHead=document.querySelector('.maker-head'),makerGrid=document.querySelector('.maker-grid');makerHead.hidden=true;const createModal=document.createElement('div');createModal.className='script-create-modal';createModal.hidden=true;createModal.innerHTML='<section class="script-create-dialog" role="dialog" aria-modal="true" aria-labelledby="createScriptTitle"><header class="script-create-dialog-head"><div><span class="kicker">NEW LIVE SCRIPT</span><h2 id="createScriptTitle">新建商品直播稿</h2><p>填写商品事实，生成后会自动加入连续播放列表。</p></div><button class="script-create-close" aria-label="关闭">×</button></header><div class="script-create-dialog-body"></div></section>';document.body.appendChild(createModal);createModal.querySelector('.script-create-dialog-body').appendChild(makerGrid);const openCreateModal=()=>{createModal.hidden=false;document.body.classList.add('modal-open');setTimeout(()=>byId('scriptName').focus(),0)},closeCreateModal=()=>{createModal.hidden=true;document.body.classList.remove('modal-open')};newScriptButton.addEventListener('click',openCreateModal);createModal.querySelector('.script-create-close').addEventListener('click',closeCreateModal);createModal.addEventListener('click',e=>{if(e.target===createModal)closeCreateModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!createModal.hidden)closeCreateModal()});
  const clean=text=>text.replace(/【[^】]+】/g,'').replace(/\n{3,}/g,'\n\n').trim();
  function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(history.slice(0,30)))}
  function titleFrom(text,continued){const name=val('scriptName','当前商品'),match=text.match(/【本次讲解核心[：:]\s*([^】]+)】/);if(match)return `${name}｜${match[1].trim().slice(0,24)}`;const first=text.replace(/【[^】]+】/g,'').split(/[。！？\n]/).map(x=>x.trim()).find(Boolean);return `${name}｜${(first||`${continued?'续写':'开场'}讲解`).slice(0,24)}`}
  function ensureProductHeading(text){const name=val('scriptName','当前商品');return /【商品名称[：:]/.test(text)?text:`【商品名称：${name}】\n${text}`}
  function add(text,continued){text=ensureProductHeading(text);byId('scriptOutput').value=text;history.unshift({id:`script-${Date.now()}`,productName:val('scriptName','当前商品'),title:titleFrom(text,continued),text,createdAt:new Date().toISOString(),audios:{}});save();render();updateGlobal()}
  const selectedVoice=item=>item.selectedVoice||Object.keys(item.audios||{})[0]||voiceOptions[0][0];
  const jobKey=(item,voice=selectedVoice(item))=>`${item.id}|${voice}`;
  function render(){const list=section.querySelector('.script-history-list');section.querySelector('.script-history-count').textContent=`共 ${history.length} 篇 · 音频按音色缓存`;continueButton.disabled=!history.length&&!byId('scriptOutput').value.trim();if(!history.length){list.innerHTML='<div class="script-history-empty">生成第一篇直播稿后，会自动保存在这里。后续可以直接续写和播放。</div>';return}list.innerHTML=history.map((item,i)=>{const voice=selectedVoice(item),generating=audioJobs.has(jobKey(item,voice)),cached=Boolean(item.audios?.[voice]),playing=item.id===playingId&&!historyAudio.paused;return `<article class="script-history-card ${item.id===playingId?'playing':''}" data-id="${item.id}"><div class="script-history-summary"><span class="script-index">${history.length-i}</span><div><div class="script-history-title">${item.title}</div><div class="script-history-meta">${new Date(item.createdAt).toLocaleString()} · ${item.text.replace(/\s/g,'').length} 字 <span class="history-cache">${cached?'已有缓存音频':'尚未合成音频'}</span></div></div><div class="script-history-actions"><select class="history-voice" data-voice-picker>${voiceOptions.map(([id,name])=>`<option value="${id}" ${id===voice?'selected':''}>${name}</option>`).join('')}</select><button class="history-generate" ${generating?'disabled':''}>${generating?'⏳ 生成中':'生成'}</button><button class="history-play" ${!cached||playing?'disabled':''}>${playing?'播放中':'▶ 播放'}</button><button class="history-open">查看/编辑</button><button class="history-delete">删除</button></div></div><pre class="script-history-preview">${item.text.replace(/&/g,'&amp;').replace(/</g,'&lt;')}</pre></article>`}).join('');if(window.LiveVoiceLibrary)window.LiveVoiceLibrary.enhanceAll(list)}
  async function ensureAudio(item,voice,force=false){item.audios=item.audios||{};if(!force&&item.audios[voice])return item.audios[voice];const key=jobKey(item,voice);if(audioJobs.has(key))return audioJobs.get(key);const job=(async()=>{render();const r=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:clean(item.text).slice(0,4800),voice,rate:'-4%',context:'live',refresh:force})}),d=await r.json();if(!r.ok)throw new Error(d.error||'音频生成失败');item.audios[voice]=d.url;item.audioRates=item.audioRates||{};item.audioRates[voice]='-4%';item.audioSentenceMarks=item.audioSentenceMarks||{};item.audioSentenceMarks[voice]=Array.isArray(d.sentenceMarks)?d.sentenceMarks:[];item.selectedVoice=voice;save();return d.url})().finally(()=>{audioJobs.delete(key);render()});audioJobs.set(key,job);render();return job}
  async function playItem(card,item){const voice=card.querySelector('.history-voice').value,button=card.querySelector('.history-play'),url=item.audios?.[voice];if(!url)return false;historyAudio.pause();button.disabled=true;button.textContent='播放中';try{item.selectedVoice=voice;save();playingId=item.id;const absoluteUrl=new URL(url,location.href).href;if(historyAudio.src===absoluteUrl){historyAudio.currentTime=0}else{historyAudio.src=url;historyAudio.load()}historyAudio.playbackRate=currentRate();await historyAudio.play();render();return true}catch(e){button.textContent=e.message;if(globalLoop)setTimeout(advanceGlobal,1200);return false}}
  function updateGlobal(){globalButton.classList.toggle('active',globalLoop);globalButton.textContent=globalLoop?'■ 停止无限播放':'▶ 无限循环播放';globalButton.disabled=!history.length;prevButton.disabled=!history.length;nextButton.disabled=!history.length;if(!globalLoop)globalStatus.textContent='从最下面开始顺序播放'}
  function stopGlobal(pause=true){globalLoop=false;globalOrder=[];if(pause){window.LiveAudioFocus?.cancelResume(historyAudio);historyAudio.pause()}updateGlobal()}
  async function playGlobalCurrent(){if(!globalLoop||!globalOrder.length)return;const id=globalOrder[globalIndex],item=history.find(x=>x.id===id);if(!item){advanceGlobal();return}const voice=selectedVoice(item);globalStatus.textContent=`等待第 ${globalIndex+1}/${globalOrder.length} 篇音频生成`;try{await ensureAudio(item,voice)}catch{advanceGlobal();return}if(!globalLoop)return;render();const card=section.querySelector(`.script-history-card[data-id="${id}"]`);if(!card){advanceGlobal();return}globalStatus.textContent=`循环播放 ${globalIndex+1}/${globalOrder.length}：${item.title}`;const ok=await playItem(card,item);if(!ok&&globalLoop)setTimeout(advanceGlobal,500)}
  function advanceGlobal(){if(!globalLoop||!globalOrder.length)return;globalIndex=(globalIndex+1)%globalOrder.length;playGlobalCurrent()}
  function startGlobal(){if(!history.length)return;globalOrder=history.slice().reverse().map(x=>x.id);globalIndex=0;globalLoop=true;updateGlobal();const jobs=globalOrder.map(id=>{const item=history.find(x=>x.id===id);return item?ensureAudio(item,selectedVoice(item),true):Promise.resolve()});globalStatus.textContent=`已触发 ${jobs.length} 篇音频生成，等待第一篇`;jobs[0].then(()=>{if(globalLoop)playGlobalCurrent()}).catch(()=>{if(globalLoop)advanceGlobal()})}
  function skipTo(direction){if(!history.length)return;const order=globalLoop&&globalOrder.length?globalOrder:history.slice().reverse().map(x=>x.id),current=order.indexOf(playingId),index=current<0?(direction>0?0:order.length-1):(current+direction+order.length)%order.length,id=order[index],item=history.find(x=>x.id===id);if(!item)return;const voice=selectedVoice(item),cached=Boolean(item.audios?.[voice]);if(!cached){globalStatus.textContent=`${item.title} 尚未生成音频`;return}historyAudio.pause();playingId=id;if(globalLoop)globalIndex=index;render();const card=section.querySelector(`.script-history-card[data-id="${id}"]`);if(card){globalStatus.textContent=`${direction>0?'下一篇':'上一篇'}：${item.title}`;playItem(card,item)}}
  prevButton.addEventListener('click',()=>skipTo(-1));nextButton.addEventListener('click',()=>skipTo(1));
  globalButton.addEventListener('click',()=>globalLoop?stopGlobal(true):startGlobal());section.addEventListener('click',e=>{if(e.target.closest('.history-play')&&globalLoop)stopGlobal(false)},true);updateGlobal();
  historyAudio.onended=()=>{playingId='';render();if(globalLoop)setTimeout(advanceGlobal,120)};
  section.addEventListener('click',e=>{const card=e.target.closest('.script-history-card');if(!card)return;const item=history.find(x=>x.id===card.dataset.id);if(!item)return;if(e.target.closest('.history-generate')){const voice=card.querySelector('.history-voice').value;item.selectedVoice=voice;save();ensureAudio(item,voice,true).catch(()=>render())}else if(e.target.closest('.history-play')){playItem(card,item)}else if(e.target.closest('.history-open')){byId('scriptOutput').value=item.text;byId('scriptOutput').dispatchEvent(new Event('input'));card.classList.toggle('expanded');byId('scriptOutput').scrollIntoView({behavior:'smooth',block:'center'})}else if(e.target.closest('.history-delete')){window.LiveAudioFocus?.cancelResume(historyAudio);historyAudio.pause();if(playingId===item.id)playingId='';history=history.filter(x=>x.id!==item.id);save();render();updateGlobal()}});
  section.addEventListener('change',e=>{if(!e.target.matches('.history-voice'))return;const card=e.target.closest('.script-history-card'),item=history.find(x=>x.id===card?.dataset.id);if(item){item.selectedVoice=e.target.value;save()}});
  function localGenerate(){const name=val('scriptName','这款商品'),selling=val('scriptSelling','使用方便、体验舒适、适合日常使用'),price=val('scriptPrice','以直播间商品卡显示为准'),audience=val('scriptAudience','正在寻找实用好物的朋友'),offer=val('scriptOffer','具体优惠和发货时间以商品详情页为准');const script=`【欢迎新进观众｜热情自然】\n家人们，刚刚进入直播间的朋友先别急着划走，今天我们正在讲${name}。如果你是${audience}，可以先听我把实际信息讲清楚。\n\n【需求与卖点｜耐心讲解】\n选择这类商品时，大家会关心是否方便、是否适合自己。${name}目前可以确认的核心卖点是：${selling}。\n\n【价格优惠｜清楚可信】\n当前价格是${price}，优惠和发货说明是：${offer}。活动和价格以商品卡及下单页面为准。\n\n【循环转场｜开放持续】\n想了解${name}的朋友可以点开商品卡或留言提问，接下来我会继续讲使用细节和适用情况。`;byId('scriptOutput').value=script;byId('scriptOutput').dispatchEvent(new Event('input'))}
  async function generate(continued){const button=continued?continueButton:formButton,original=button.textContent;button.disabled=true;button.textContent=continued?'正在续写下一篇…':'正在生成…';const out=byId('scriptOutput'),previous=continued&&history.length?history[0].text:out.value.trim(),payload={name:val('scriptName','这款商品'),selling:val('scriptSelling','使用方便、体验舒适、适合日常使用'),price:val('scriptPrice','以直播间商品卡显示为准'),audience:val('scriptAudience','正在寻找实用好物的朋友'),offer:val('scriptOffer','具体优惠和发货时间以商品详情页为准'),targetLength:Number(lengthInput.value)||1000,continuation:continued,previousScript:continued?previous:''};try{const r=await fetch('/api/generate-script',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error((await r.json()).error||'生成失败');out.value='';const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const events=buffer.split('\n\n');buffer=events.pop()||'';for(const event of events){const line=event.split('\n').find(x=>x.startsWith('data: '));if(!line)continue;const d=JSON.parse(line.slice(6));if(d.delta){out.value+=d.delta;out.scrollTop=out.scrollHeight;byId('scriptLength').textContent=`${out.value.replace(/\s/g,'').length} 字 · 正在${continued?'续写':'生成'}…`}}}out.value=out.value.replace(/拜拜|再见|下期见|感谢观看|视频结束|关注我下期见|晚安|好了[，,、 ]*接下去要介绍别的了?|接下来介绍别的商品|下面换一个商品|接下来介绍另一个商品/gi,'继续留在直播间，我们接着讲当前商品');out.dispatchEvent(new Event('input'));byId('scriptLength').textContent=`${out.value.replace(/\s/g,'').length} 字 · ${continued?'续写稿':'直播稿'}生成完成`;add(out.value,continued)}catch(e){if(!continued){localGenerate();add(out.value,false)}byId('scriptLength').textContent+=` · ${e.message}`}finally{button.disabled=false;button.textContent=original;render()}}
  formButton.addEventListener('click',()=>generate(false));continueButton.addEventListener('click',()=>generate(true));byId('copyScript').addEventListener('click',async()=>{const out=byId('scriptOutput');if(!out.value)return;await navigator.clipboard.writeText(out.value);byId('copyScript').textContent='已复制';setTimeout(()=>byId('copyScript').textContent='复制全文',1200)});byId('scriptOutput').addEventListener('input',e=>{byId('scriptLength').textContent=`${e.target.value.replace(/\s/g,'').length} 字 · 已编辑`;continueButton.disabled=!history.length&&!e.target.value.trim()});render();
})();
