(function(){
  const out=document.getElementById('scriptOutput');if(!out)return;
  const box=document.createElement('div');box.className='segment-guide';box.innerHTML='<div class="segment-title"><span>直播段落导航</span><small id="activeSegmentText">点击标题跳到段落起点</small></div><div id="segmentList"><span class="segment-empty">生成直播稿后，这里会显示段落标记。</span></div>';out.parentElement.appendChild(box);
  const rules=[['欢迎|开场|留人|新进','欢迎留人','承接新进观众','热情明亮，语速略快'],['需求|痛点','建立需求','说出观众真实问题','共情自然，像聊天'],['卖点|核心|特点','核心卖点','解释商品核心价值','清晰笃定，重点加重'],['场景|使用','使用场景','帮助观众想象使用过程','轻松有画面感'],['互动|问答|留言','互动问答','邀请留言并回答高频问题','亲切灵活，句子短'],['价格|优惠|发货','价格优惠','讲清价格活动与时效','适当放慢，数字清楚'],['风险|提示|售后','风险提示','说明资料边界和售后','平和严谨'],['总结|循环|转场|继续','循环转场','重新接待新进观众','自然收束后抬起语气']];let segments=[];
  function scrollToIndex(index){out.focus();out.setSelectionRange(index,index);const lines=out.value.slice(0,index).split('\n').length,total=Math.max(1,out.value.split('\n').length);out.scrollTop=(lines/total)*(out.scrollHeight-out.clientHeight);const seg=segments.find(s=>s.index===index);if(seg)window.dispatchEvent(new CustomEvent('segment-jump',{detail:{ratio:seg.ratio,title:seg.title}}))}
  function activate(ratio){if(!segments.length)return;let active=segments[0];for(const s of segments)if(s.ratio<=ratio)active=s;document.querySelectorAll('.segment-card').forEach((el,i)=>el.classList.toggle('active',segments[i]===active));document.getElementById('activeSegmentText').textContent=`正在播报：${active.title} · ${active.tone}`}
  function render(){const text=out.value.trim(),list=document.getElementById('segmentList');if(!text){segments=[];list.innerHTML='<span class="segment-empty">生成直播稿后，这里会显示段落标记。</span>';return}const heads=[...out.value.matchAll(/(?:^|\n)\s*[【\[]([^】\]]+)[】\]]\s*/g)];segments=heads.map(h=>{const title=h[1],rule=rules.find(r=>new RegExp(r[0]).test(title))||['','直播讲解','补充商品信息','自然清晰'];return{title,index:h.index,ratio:h.index/Math.max(1,out.value.length),role:rule[1],purpose:rule[2],tone:rule[3]}});if(!segments.length)segments=[{title:'连续直播稿',index:0,ratio:0,role:'直播讲解',purpose:'完整连续讲解',tone:'自然清晰'}];list.innerHTML=segments.map((s,i)=>`<button class="segment-card" data-index="${s.index}"><div class="segment-top"><b>${i+1}. ${s.title}</b><em>${s.role}</em></div><span>作用：${s.purpose}</span><span>语气：${s.tone}</span></button>`).join('');list.querySelectorAll('.segment-card').forEach(el=>el.onclick=()=>scrollToIndex(Number(el.dataset.index)));activate(0)}
  out.addEventListener('input',render);window.addEventListener('narration-progress',e=>activate(e.detail.ratio));render();
})();
