(function(){
  const voices=[
    {id:'zh_female_vivi_uranus_bigtts',name:'Vivi 2.0',gender:'female',desc:'语调平稳、咬字柔和，自带治愈安抚力的女声音色',tags:['中英混','通用场景'],icon:'V'},
    {id:'zh_female_xiaohe_uranus_bigtts',name:'小何 2.0',gender:'female',desc:'声线甜美有活力，活泼开朗，笑容明媚',tags:['中英混','直播带货'],icon:'何'},
    {id:'zh_male_wenrouahu_uranus_bigtts',name:'温暖阿虎 2.0',gender:'male',desc:'声线阳光温暖、语气亲切，活力满满的少年音',tags:['中英混','通用场景'],icon:'虎'},
    {id:'zh_male_jieshuoxiaoming_uranus_bigtts',name:'解说小明 2.0',gender:'male',desc:'语速明快、中气十足，充满激情与感染力的解说男声',tags:['中英混','视频配音'],icon:'明'},
    {id:'zh_female_wenroumama_uranus_bigtts',name:'温柔妈妈 2.0',gender:'female',desc:'语调舒缓、咬字温润，自带母性柔光的治愈女声',tags:['中英混','通用场景'],icon:'妈'},
    {id:'zh_female_gaolengyujie_uranus_bigtts',name:'高冷御姐 2.0',gender:'female',desc:'成熟清晰、自然利落，适合商品卖点和价格讲解',tags:['中文','直播带货'],icon:'御',verified:true},
    {id:'zh-CN-XiaoxiaoNeural',name:'晓晓 · 备用',gender:'female',desc:'Edge 在线女声，火山音色不可用时的稳定备用方案',tags:['中文','备用音色'],icon:'晓',fallback:true},
    {id:'zh-CN-XiaoyiNeural',name:'晓伊 · 备用',gender:'female',desc:'活力女声，适合轻快的互动回应',tags:['中文','备用音色'],icon:'伊',fallback:true},
    {id:'zh-CN-YunxiNeural',name:'云希 · 备用',gender:'male',desc:'清爽阳光男声，适合年轻化商品',tags:['中文','备用音色'],icon:'希',fallback:true},
    {id:'zh-CN-YunjianNeural',name:'云健 · 备用',gender:'male',desc:'沉稳有力男声，适合耐用品和功能讲解',tags:['中文','备用音色'],icon:'健',fallback:true}
  ];
  document.body.insertAdjacentHTML('beforeend','<div class="voice-modal" id="voiceModal" hidden><section class="voice-dialog" role="dialog" aria-modal="true" aria-labelledby="voiceTitle"><header class="voice-dialog-head"><h2 id="voiceTitle">选择音色，合成试听</h2><button class="voice-close" aria-label="关闭">×</button></header><nav class="voice-tabs"><button class="voice-tab active">音色库</button><button class="voice-tab">预付费音色</button><button class="voice-tab">后付费音色</button></nav><div class="voice-tools"><input class="voice-search" placeholder="⌕  在音色库中搜索音色名称或音色 ID"><div class="voice-filters"><button class="voice-filter active" data-gender="all">全部</button><button class="voice-filter" data-gender="female">女声</button><button class="voice-filter" data-gender="male">男声</button></div></div><div class="voice-list"></div><footer class="voice-dialog-foot"><span><b id="voiceSelectedCount">已选 1 个</b>　<span class="voice-preview-state"></span></span><div class="voice-actions"><button class="voice-cancel">取消</button><button class="voice-confirm">确定</button></div></footer><audio id="voicePreviewAudio"></audio></section></div>');
  const modal=document.getElementById('voiceModal'),list=modal.querySelector('.voice-list'),search=modal.querySelector('.voice-search'),preview=modal.querySelector('#voicePreviewAudio'),previewState=modal.querySelector('.voice-preview-state');let target=null,chosen='',gender='all';
  function voiceById(id){return voices.find(v=>v.id===id)||voices[5]}
  function render(){const q=search.value.trim().toLowerCase(),items=voices.filter(v=>(gender==='all'||v.gender===gender)&&(!q||`${v.name} ${v.id} ${v.desc} ${v.tags.join(' ')}`.toLowerCase().includes(q)));list.innerHTML=items.length?items.map(v=>`<div class="voice-row ${v.id===chosen?'selected':''}" data-id="${v.id}"><div class="voice-main"><div class="voice-avatar">${v.icon}<button class="voice-play" title="试听">▶</button></div><div><div class="voice-title">${v.name}${v.verified?' <small style="color:#7656ff">已验证</small>':''}</div><div class="voice-desc">${v.desc}</div></div></div><div class="voice-tags">${v.tags.map(t=>`<span class="voice-tag">${t}</span>`).join('')}</div><span class="voice-radio"></span></div>`).join(''):'<div class="voice-empty">没有找到匹配的音色</div>'}
  async function playSample(v){preview.pause();previewState.textContent=`正在合成 ${v.name} 试听…`;try{const r=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:'欢迎来到直播间，这款商品我给大家认真讲一讲，喜欢自然声音的朋友可以听听看。',voice:v.id,context:'reply'})}),d=await r.json();if(!r.ok)throw new Error(d.error||'试听失败');preview.src=d.url;await preview.play();previewState.textContent=d.warning||`正在试听 ${v.name}`}catch(e){previewState.textContent=e.message}}
  function enhance(select){if(!select||select._voiceButton)return;select.classList.add('voice-native-select');const current=voiceById(select.value),btn=document.createElement('button');btn.type='button';btn.className='voice-picker-btn';if(select.classList.contains('history-voice'))btn.classList.add('voice-picker-compact');btn.innerHTML=`<span class="voice-picker-dot">${current.icon}</span><span class="voice-picker-name">${current.name}</span><span class="voice-picker-tip">选择音色 ›</span>`;select.insertAdjacentElement('afterend',btn);btn.onclick=()=>{target=select;chosen=select.value;search.value='';gender='all';modal.querySelectorAll('.voice-filter').forEach((b,i)=>b.classList.toggle('active',i===0));render();modal.hidden=false;search.focus()};select._voiceButton=btn}
  function close(){modal.hidden=true;preview.pause();previewState.textContent=''}
  list.onclick=e=>{const row=e.target.closest('.voice-row');if(!row)return;chosen=row.dataset.id;render();if(e.target.closest('.voice-play'))playSample(voiceById(chosen))};search.oninput=render;modal.querySelectorAll('.voice-filter').forEach(b=>b.onclick=()=>{gender=b.dataset.gender;modal.querySelectorAll('.voice-filter').forEach(x=>x.classList.toggle('active',x===b));render()});modal.querySelector('.voice-close').onclick=close;modal.querySelector('.voice-cancel').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};modal.querySelector('.voice-confirm').onclick=()=>{if(target&&chosen){target.value=chosen;target.dispatchEvent(new Event('change',{bubbles:true}));const v=voiceById(chosen);target._voiceButton.innerHTML=`<span class="voice-picker-dot">${v.icon}</span><span class="voice-picker-name">${v.name}</span><span class="voice-picker-tip">已选音色 ✓</span>`}close()};
  function enhanceAll(root=document){root.querySelectorAll('#voiceSelect,#scriptVoice,.history-voice,[data-voice-picker]').forEach(s=>{voices.forEach(v=>{if(![...s.options].some(o=>o.value===v.id))s.add(new Option(v.name,v.id))});enhance(s)})}
  window.LiveVoiceLibrary={enhance,enhanceAll,voices};enhanceAll();
})();
